module StorageUtilityMessage
{
    class StorageOrder
    {
        String storage_address
        String file_uri
        String content_unit_uri
        String session_id
        UInt64 seconds
        TimePoint time_point
    }

    class SignedStorageOrder
    {
        StorageOrder order
        Authority authorization
    }

    class Authority
    {
        String address
        String signature
    }

    class SignRequest
    {
        String private_key
        StorageOrder order
    }

    class VerificationResponse
    {
        StorageOrder storage_order
        String address
    }

    class RemoteError { String message }
}
////4
