module BlockchainMessage
{
    type Join {}
    type Drop {}
    type Error {}
    type TimerOut {}

    class Other
    {
        Extension contents
    }

    class Block
    {
        String previous
        String tempContents
    }
}
