module CommanderMessage
{
    class NumberValue
    {
        UInt64 value
    }

    class NumberPair
    {
        UInt64 first
        UInt64 second
    }

    class Coin
    {
        UInt64 whole
        UInt64 fraction
    }

    class Account
    {
        String address
        Coin balance
    }

    class AccountResponse
    {
        String address
        Coin balance
        Coin confirmed_balance
        Coin unconfirmed_sent
        Coin unconfirmed_received
    }

    class Done
    {
    }

    class Failed
    {
        String message
    }

    class HeadBlockRequest
    {}

    class AccountRequest
    {
        String address
    }

    class AccountsRequest
    {}

    class AccountsResponse
    {
        Array AccountResponse accounts
    }

    class AccountHistoryRequest
    {
        String address
        UInt64 start_block_index
        UInt64 max_block_count
    }

    class AccountHistory
    {
        Array Object history
    }

    enum AccountHistoryItemType
    {
        received
        received_fee
        sent
        sent_fee
        rewarded
    }
    class AccountHistoryReceived
    {
        UInt64 block_index
        UInt64 confirmations
        AccountHistoryItemType item_type
        TimePoint timestamp
        String from
        Coin amount
        String message
    }
    class AccountHistoryReceivedFee
    {
        UInt64 block_index
        UInt64 confirmations
        AccountHistoryItemType item_type
        TimePoint timestamp
        String from
        Coin amount
    }
    class AccountHistorySent
    {
        UInt64 block_index
        UInt64 confirmations
        AccountHistoryItemType item_type
        TimePoint timestamp
        String to
        Coin amount
        String message
    }
    class AccountHistorySentFee
    {
        UInt64 block_index
        UInt64 confirmations
        AccountHistoryItemType item_type
        TimePoint timestamp
        String to
        Coin amount
    }
    class AccountHistoryRewarded
    {
        UInt64 block_index
        UInt64 confirmations
        AccountHistoryItemType item_type
        TimePoint timestamp
        Coin amount
    }

    class ImportAccount
    {
        String address
    }
}
////2
