module PubliqNodeMessage
{
    type Join {}
    type Drop {}
    type Error {}
    type TimerOut {}

    class Hellow
    {
        String text
    }

    class Broadcast
    {
        Object payload
    }
}
