module BlockchainMessage
{
    //  standard socket messages
    type Join {} // 0
    type Drop {} // 1
    type Error {} // 2

    //  dummy, testing
    class Hellow // 3
    {
        String text
        UInt64 index
    }

    //  container messages
    class Broadcast // 4
    {
        Object value
    }

    //  special testing shutdown message
    class Shutdown {} // 5

    ///
    /// RPC interface
    ///
    //  response codes
    class Done {} // 6

    class Failed // 7
    {
        String message
    }

    //  GetChainInfo request, response should be ChainInfo
    class GetChainInfo {} // 8

    //  ChainInfo
    class ChainInfo // 9
    {
        UInt64 length
    }

    //  request to calculate the checksum
    class CalculateChecksum // 10
    {
        Object value
    }

    class Checksum // 11
    {
        String sha256_2x
    }
    // .
    // .
    class GetActions // 12
    {
        UInt64 start_index
    }

    class Action // 13
    {
        UInt64 index
        Object item
    }

    class Actions // 14
    {
        Array Action list
    }

    //  save HTTPObject in distributed storage, response
    //  will be Checksum
    class HTTPObject // 15
    {
        String mimetype
        String body
    }

    //  response will be HTTPObject
    class GetFromStorage // 16
    {
        Checksum path
    }

    //  this is admin tool for RPC testing
    class SubmitActions // 17
    {
        Object item
    }

    class Bin64 // 18
    {
        String value
    }

    class TransactionHash // 29
    {
        Bin64 value
        UInt64 block_index
    }

    class Address // 20
    {
        String public_key
    }

    class Coin // 21
    {
        UInt64 value
    }

    class Transaction // 22
    {
        TimePoint tm
        UInt64 nonce
        Coin fee
        Object obj
    }

    class SignedTransaction // 23
    {
        Transaction obj
        String signature
    }

    class Transfer // 24
    {
        Address from
        Address to
        Coin amount
    }

    class RevertActionAt // 25
    {
        UInt64 index
        Object item
    }

    class RevertLastAction {} // 26

    //  .
    class Reward // 27
    {
        Coin amount
        Address to
    }

    //  .
    class NewArticle // 28
    {
        String title
        Array String hash
    }

    class GetHash
    {
        Object item
    }

    class HashResult
    {
        String base58_hash
        Object item
    }

    class RemoteError
    {
        String message
    }

    class InvalidAddress
    {
        Address item
    }
}
