module BlockchainMessage
{
    type Join {}
    type Drop {}
    type Error {}

    class Hellow
    {
        String text
        UInt64 index
    }

    class Broadcast
    {
        Object payload
    }

    class Shutdown {}

    class GetChainInfo {}

    class ChainInfo
    {
        UInt64 length
    }

    class Transaction
    {
        Array String inputs

    }
}
