module StorageTypes
{
    class FileUriHolders
    {
        Set String addresses
    }

    class ContentUnitSponsoredInformation
    {
        String uri
        Array SponsoredInformation sponsored_informations
        Array TimePoint time_points_used
        Array UInt64 index_si
    }

    class SponsoredInformation
    {
        TimePoint start_time_point
        TimePoint end_time_point
        Coin amount
        UInt64 time_points_used_before
        String sponsor_address
        String transaction_hash
        Bool cancelled
        Optional SponsoringScope scope
    }
    enum SponsoringScope
    {
        content
        global
    }

    class SponsoredInformationHeaders
    {
        Hash String SponsoredInformationHeader expirations
    }

    class SponsoredInformationHeader
    {
        String uri
        String transaction_hash
        UInt64 block_number
        Coin manually_cancelled
    }

    class Coin
    {
        UInt64 whole
        UInt64 fraction
    }

    class TransactionHashToBlockNumber
    {
        String transaction_hash
        UInt64 block_number
    }

    class FileRequest
    {
        String file_uri
        String channel_address
    }

    ///
    // Slave message types below
    ///
    class StorageFile
    {
        Extension storage_file
    }

    class StorageFileDelete
    {
        Extension storage_file_delete
    }

    class SetVerifiedChannels
    {
        Array String channel_addresses
    }

    class FileUrisRequest
    {}

    class ContainerMessage
    {
        Extension package
    }
}
////3
