module StorageTypes
{
    class FileUriHolders
    {
        Set String addresses
    }

    class ContentUnitSponsoredInformation
    {
        String uri
        Array SponsoredInformation sponsored_informations
        Array TimePoint time_points_used
        Array UInt64 index_si
    }

    class SponsoredInformation
    {
        TimePoint start_time_point
        TimePoint end_time_point
        Coin amount
        UInt64 time_points_used_before
        String sponsor_address
        String transaction_hash
        Bool cancelled
    }

    class SponsoredInformationHeaders
    {
        Hash String SponsoredInformationHeader expirations
    }
    class SponsoredInformationHeader
    {
        String uri
        String transaction_hash
        UInt64 block_number
        Coin manually_cancelled
    }

    class Coin
    {
        UInt64 whole
        UInt64 fraction
    }
}
